### PR TITLE
Remove ko.calendar.version from build

### PR DESCRIPTION
**Pull request by ready4god2513**
Fixes issues brought up in #9

### CODE REVIEW

**Comment by jakiestfu** [comment]
@mpalmerlee Can you please merge and then create a new release titled `v0.1.11` ?

**Comment by jakiestfu** [comment]
Thanks @twgibbons. Do you mind cutting a release for it as `v0.2.11` ?

**Comment by twgibbons** [comment]
Yup, taken care of.

**Comment by twgibbons** [comment]
Thanks, guys.

**Comment by jakiestfu** [comment]
Thank you as well :beers:

**Pull request merged**
